### ISSUE TITLE
Calendar - Fix calendar tooltip shifting when adding a class

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc-projects/AntAlmanac#117] opened 2020-07-13 02:51 UTC
To reproduce: Add a course, like MATH 2A (44000 from Spring 2020) then open the tooltip for it. Then, search for AFAM 40C (20210 from Spring 2020) and add it. The tootip will suddenly shift to the AFAM events.

**Comment by EricPedley** [comment] 2022-01-30 07:54
Can't reproduce this bug on the latest version. Can someone else confirm and then we can close this issue?

**Comment by ChaseC99** [comment] 2022-01-30 08:12
You're right, I can't reproduce this either. @falsidge and I were working on another color issue last year that might have fixed this (#197 and #198).

Marking this as closed!

**Closed by ChaseC99** 2022-01-30 08:12 UTC
Labels: bug
